collections:
  projects:
    output: true
    permalink: /project/:path/
  techniques:
    output: true
    permalink: /technieken/:path/

exclude:
  - bower_components/bootstrap/js
  - bower_components/bootstrap/less
  - bower_components/jquery/test
  - bower_components/jquery/speed

gems:
  - jekyll-sitemap
