collections:
  projects:
    output: true
    permalink: /projecten/:path.html
  techniques:
    output: true
    permalink: /technieken/:path.html

exclude:
  - bower_components/bootstrap/js
  - bower_components/bootstrap/less
  - bower_components/jquery/test
  - bower_components/jquery/speed
  - vendor

gems:
  - jekyll-sitemap
